/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Language = { 'hindi' : null } |
  { 'portuguese' : null } |
  { 'japanese' : null } |
  { 'italian' : null } |
  { 'punjabi' : null } |
  { 'spanish' : null } |
  { 'german' : null } |
  { 'arabic' : null } |
  { 'french' : null } |
  { 'mandarin' : null };
export interface Lesson {
  'lessonId' : string,
  'completed' : boolean,
  'language' : Language,
  'category' : string,
}
export interface Profile {
  'username' : string,
  'selectedLanguage' : Language,
  'learningGoal' : string,
}
export interface Progress {
  'totalLessonsCompleted' : bigint,
  'dailyStreak' : bigint,
}
export interface TutorSettings {
  'personalityStyle' : string,
  'tutorName' : string,
}
export type VocabularyStatus = { 'new' : null } |
  { 'learning' : null } |
  { 'known' : null };
export interface VocabularyWord {
  'status' : VocabularyStatus,
  'word' : string,
  'language' : Language,
  'translation' : string,
}
export interface _SERVICE {
  'addVocabulary' : ActorMethod<[Array<VocabularyWord>], undefined>,
  'completeLesson' : ActorMethod<[string, Language, string], undefined>,
  'getLessons' : ActorMethod<[], Array<Lesson>>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getProgress' : ActorMethod<[], [] | [Progress]>,
  'getTutorSettings' : ActorMethod<[], [] | [TutorSettings]>,
  'getVocabulary' : ActorMethod<[Principal], Array<VocabularyWord>>,
  'saveProfile' : ActorMethod<[string, Language, string], undefined>,
  'saveTutorSettings' : ActorMethod<[string, string], undefined>,
  'updateVocabularyStatus' : ActorMethod<[string, VocabularyStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];