/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VocabularyStatus = IDL.Variant({
  'new' : IDL.Null,
  'learning' : IDL.Null,
  'known' : IDL.Null,
});
export const Language = IDL.Variant({
  'hindi' : IDL.Null,
  'portuguese' : IDL.Null,
  'japanese' : IDL.Null,
  'italian' : IDL.Null,
  'punjabi' : IDL.Null,
  'spanish' : IDL.Null,
  'german' : IDL.Null,
  'arabic' : IDL.Null,
  'french' : IDL.Null,
  'mandarin' : IDL.Null,
});
export const VocabularyWord = IDL.Record({
  'status' : VocabularyStatus,
  'word' : IDL.Text,
  'language' : Language,
  'translation' : IDL.Text,
});
export const Lesson = IDL.Record({
  'lessonId' : IDL.Text,
  'completed' : IDL.Bool,
  'language' : Language,
  'category' : IDL.Text,
});
export const Profile = IDL.Record({
  'username' : IDL.Text,
  'selectedLanguage' : Language,
  'learningGoal' : IDL.Text,
});
export const Progress = IDL.Record({
  'totalLessonsCompleted' : IDL.Nat,
  'dailyStreak' : IDL.Nat,
});
export const TutorSettings = IDL.Record({
  'personalityStyle' : IDL.Text,
  'tutorName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addVocabulary' : IDL.Func([IDL.Vec(VocabularyWord)], [], []),
  'completeLesson' : IDL.Func([IDL.Text, Language, IDL.Text], [], []),
  'getLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getProgress' : IDL.Func([], [IDL.Opt(Progress)], ['query']),
  'getTutorSettings' : IDL.Func([], [IDL.Opt(TutorSettings)], ['query']),
  'getVocabulary' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VocabularyWord)],
      ['query'],
    ),
  'saveProfile' : IDL.Func([IDL.Text, Language, IDL.Text], [], []),
  'saveTutorSettings' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateVocabularyStatus' : IDL.Func([IDL.Text, VocabularyStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VocabularyStatus = IDL.Variant({
    'new' : IDL.Null,
    'learning' : IDL.Null,
    'known' : IDL.Null,
  });
  const Language = IDL.Variant({
    'hindi' : IDL.Null,
    'portuguese' : IDL.Null,
    'japanese' : IDL.Null,
    'italian' : IDL.Null,
    'punjabi' : IDL.Null,
    'spanish' : IDL.Null,
    'german' : IDL.Null,
    'arabic' : IDL.Null,
    'french' : IDL.Null,
    'mandarin' : IDL.Null,
  });
  const VocabularyWord = IDL.Record({
    'status' : VocabularyStatus,
    'word' : IDL.Text,
    'language' : Language,
    'translation' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'lessonId' : IDL.Text,
    'completed' : IDL.Bool,
    'language' : Language,
    'category' : IDL.Text,
  });
  const Profile = IDL.Record({
    'username' : IDL.Text,
    'selectedLanguage' : Language,
    'learningGoal' : IDL.Text,
  });
  const Progress = IDL.Record({
    'totalLessonsCompleted' : IDL.Nat,
    'dailyStreak' : IDL.Nat,
  });
  const TutorSettings = IDL.Record({
    'personalityStyle' : IDL.Text,
    'tutorName' : IDL.Text,
  });
  
  return IDL.Service({
    'addVocabulary' : IDL.Func([IDL.Vec(VocabularyWord)], [], []),
    'completeLesson' : IDL.Func([IDL.Text, Language, IDL.Text], [], []),
    'getLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getProgress' : IDL.Func([], [IDL.Opt(Progress)], ['query']),
    'getTutorSettings' : IDL.Func([], [IDL.Opt(TutorSettings)], ['query']),
    'getVocabulary' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VocabularyWord)],
        ['query'],
      ),
    'saveProfile' : IDL.Func([IDL.Text, Language, IDL.Text], [], []),
    'saveTutorSettings' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateVocabularyStatus' : IDL.Func([IDL.Text, VocabularyStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };