/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Lesson {
    lessonId: string;
    completed: boolean;
    language: Language;
    category: string;
}
export interface VocabularyWord {
    status: VocabularyStatus;
    word: string;
    language: Language;
    translation: string;
}
export interface Progress {
    totalLessonsCompleted: bigint;
    dailyStreak: bigint;
}
export interface Profile {
    username: string;
    selectedLanguage: Language;
    learningGoal: string;
}
export interface TutorSettings {
    personalityStyle: string;
    tutorName: string;
}
export enum Language {
    hindi = "hindi",
    portuguese = "portuguese",
    japanese = "japanese",
    italian = "italian",
    punjabi = "punjabi",
    spanish = "spanish",
    german = "german",
    arabic = "arabic",
    french = "french",
    mandarin = "mandarin"
}
export enum VocabularyStatus {
    new_ = "new",
    learning = "learning",
    known = "known"
}
export interface backendInterface {
    addVocabulary(words: Array<VocabularyWord>): Promise<void>;
    completeLesson(lessonId: string, language: Language, category: string): Promise<void>;
    getLessons(): Promise<Array<Lesson>>;
    getProfile(): Promise<Profile | null>;
    getProgress(): Promise<Progress | null>;
    getTutorSettings(): Promise<TutorSettings | null>;
    getVocabulary(user: Principal): Promise<Array<VocabularyWord>>;
    saveProfile(username: string, language: Language, goal: string): Promise<void>;
    saveTutorSettings(name: string, style: string): Promise<void>;
    updateVocabularyStatus(word: string, newStatus: VocabularyStatus): Promise<void>;
}
import type { Language as _Language, Lesson as _Lesson, Profile as _Profile, Progress as _Progress, TutorSettings as _TutorSettings, VocabularyStatus as _VocabularyStatus, VocabularyWord as _VocabularyWord } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addVocabulary(arg0: Array<VocabularyWord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVocabulary(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVocabulary(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async completeLesson(arg0: string, arg1: Language, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeLesson(arg0, to_candid_Language_n6(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeLesson(arg0, to_candid_Language_n6(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async getLessons(): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessons();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessons();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgress(): Promise<Progress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTutorSettings(): Promise<TutorSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTutorSettings();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTutorSettings();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVocabulary(arg0: Principal): Promise<Array<VocabularyWord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVocabulary(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVocabulary(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveProfile(arg0: string, arg1: Language, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(arg0, to_candid_Language_n6(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(arg0, to_candid_Language_n6(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async saveTutorSettings(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTutorSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTutorSettings(arg0, arg1);
            return result;
        }
    }
    async updateVocabularyStatus(arg0: string, arg1: VocabularyStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVocabularyStatus(arg0, to_candid_VocabularyStatus_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVocabularyStatus(arg0, to_candid_VocabularyStatus_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Language_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Lesson_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lesson): Lesson {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_VocabularyStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VocabularyStatus): VocabularyStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_VocabularyWord_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VocabularyWord): VocabularyWord {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Progress]): Progress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TutorSettings]): TutorSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lessonId: string;
    completed: boolean;
    language: _Language;
    category: string;
}): {
    lessonId: string;
    completed: boolean;
    language: Language;
    category: string;
} {
    return {
        lessonId: value.lessonId,
        completed: value.completed,
        language: from_candid_Language_n11(_uploadFile, _downloadFile, value.language),
        category: value.category
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    selectedLanguage: _Language;
    learningGoal: string;
}): {
    username: string;
    selectedLanguage: Language;
    learningGoal: string;
} {
    return {
        username: value.username,
        selectedLanguage: from_candid_Language_n11(_uploadFile, _downloadFile, value.selectedLanguage),
        learningGoal: value.learningGoal
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _VocabularyStatus;
    word: string;
    language: _Language;
    translation: string;
}): {
    status: VocabularyStatus;
    word: string;
    language: Language;
    translation: string;
} {
    return {
        status: from_candid_VocabularyStatus_n21(_uploadFile, _downloadFile, value.status),
        word: value.word,
        language: from_candid_Language_n11(_uploadFile, _downloadFile, value.language),
        translation: value.translation
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hindi: null;
} | {
    portuguese: null;
} | {
    japanese: null;
} | {
    italian: null;
} | {
    punjabi: null;
} | {
    spanish: null;
} | {
    german: null;
} | {
    arabic: null;
} | {
    french: null;
} | {
    mandarin: null;
}): Language {
    return "hindi" in value ? Language.hindi : "portuguese" in value ? Language.portuguese : "japanese" in value ? Language.japanese : "italian" in value ? Language.italian : "punjabi" in value ? Language.punjabi : "spanish" in value ? Language.spanish : "german" in value ? Language.german : "arabic" in value ? Language.arabic : "french" in value ? Language.french : "mandarin" in value ? Language.mandarin : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    learning: null;
} | {
    known: null;
}): VocabularyStatus {
    return "new" in value ? VocabularyStatus.new : "learning" in value ? VocabularyStatus.learning : "known" in value ? VocabularyStatus.known : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VocabularyWord>): Array<VocabularyWord> {
    return value.map((x)=>from_candid_VocabularyWord_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lesson>): Array<Lesson> {
    return value.map((x)=>from_candid_Lesson_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Language_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_VocabularyStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VocabularyStatus): _VocabularyStatus {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_VocabularyWord_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VocabularyWord): _VocabularyWord {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: VocabularyStatus;
    word: string;
    language: Language;
    translation: string;
}): {
    status: _VocabularyStatus;
    word: string;
    language: _Language;
    translation: string;
} {
    return {
        status: to_candid_VocabularyStatus_n4(_uploadFile, _downloadFile, value.status),
        word: value.word,
        language: to_candid_Language_n6(_uploadFile, _downloadFile, value.language),
        translation: value.translation
    };
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VocabularyStatus): {
    new: null;
} | {
    learning: null;
} | {
    known: null;
} {
    return value == VocabularyStatus.new ? {
        new_: null
    } : value == VocabularyStatus.learning ? {
        learning: null
    } : value == VocabularyStatus.known ? {
        known: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    hindi: null;
} | {
    portuguese: null;
} | {
    japanese: null;
} | {
    italian: null;
} | {
    punjabi: null;
} | {
    spanish: null;
} | {
    german: null;
} | {
    arabic: null;
} | {
    french: null;
} | {
    mandarin: null;
} {
    return value == Language.hindi ? {
        hindi: null
    } : value == Language.portuguese ? {
        portuguese: null
    } : value == Language.japanese ? {
        japanese: null
    } : value == Language.italian ? {
        italian: null
    } : value == Language.punjabi ? {
        punjabi: null
    } : value == Language.spanish ? {
        spanish: null
    } : value == Language.german ? {
        german: null
    } : value == Language.arabic ? {
        arabic: null
    } : value == Language.french ? {
        french: null
    } : value == Language.mandarin ? {
        mandarin: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<VocabularyWord>): Array<_VocabularyWord> {
    return value.map((x)=>to_candid_VocabularyWord_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
